# coding: utf-8
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as ss

df_katka, df_michal, df_pavel = pd.read_csv("katka.csv"), pd.read_csv("michal.csv"), pd.read_csv("pavel.csv")
df_katka.rename(columns = {"impact": "impact_KR", "originality": "originality_KR" }, inplace = True)
df_michal.rename(columns = {"impact": "impact_MK", "originality": "originality_MK" }, inplace = True)
df_pavel.rename(columns = {"impact": "impact_PD", "originality": "originality_PD" }, inplace = True)
df = pd.concat( [ df_katka, df_michal, df_pavel ], axis = 1)
df['impact'] = df['impact_KR'] + df['impact_MK'] + df['impact_PD']
df['originality'] = df['originality_KR'] + df['originality_MK'] + df['originality_PD']

df.to_excel("data.xlsx")
df.sort_values(by=["impact", "originality"], ascending=False).to_excel("impact.xlsx")
df.sort_values(by=["originality", "impact"], ascending=False).to_excel("originality.xlsx")

fig, axes = plt.subplots( nrows = 4, ncols = 2, figsize = (4, 7) )
sns.histplot(x="originality", data = df, ax = axes[0,0] )
sns.histplot(x="originality_KR", data = df, ax = axes[1,0] )
sns.histplot(x="originality_MK", data = df, ax = axes[2,0] )
sns.histplot(x="originality_PD", data = df, ax = axes[3,0] )
sns.histplot(x="impact", data = df, ax = axes[0,1] )
sns.histplot(x="impact_KR", data = df, ax = axes[1,1] )
sns.histplot(x="impact_MK", data = df, ax = axes[2,1] )
sns.histplot(x="impact_PD", data = df, ax = axes[3,1] )
plt.tight_layout()
sh, p = ss.shapiro(df['originality'])
axes[0, 0].text( x = 21  , y = 40, s = f"p = {p:0.3f}" )
sh, p = ss.shapiro(df['originality_KR'])
axes[1, 0].text( x =  7  , y = 35, s = f"p = {p:0.3f}" )
sh, p = ss.shapiro(df['originality_MK'])
axes[2, 0].text( x =  7.4, y = 50, s = f"p = {p:0.3f}" )
sh, p = ss.shapiro(df['originality_PD'])
axes[3, 0].text( x =  8, y = 50, s = f"p = {p:0.3f}" )
sh, p = ss.shapiro(df['impact'])
axes[0, 1].text( x = 21.5, y = 40, s = f"p = {p:0.3f}" )
sh, p = ss.shapiro(df['impact_KR'])
axes[1, 1].text( x =  8  , y = 40, s = f"p = {p:0.3f}" )
sh, p = ss.shapiro(df['impact_MK'])
axes[2, 1].text( x =  7  , y = 45, s = f"p = {p:0.3f}" )
sh, p = ss.shapiro(df['impact_PD'])
axes[3, 1].text( x =  8  , y = 50, s = f"p = {p:0.3f}" )
#plt.suptitle("Normality testing")
plt.show()

fig, axes = plt.subplots( nrows = 2, ncols = 2, figsize = (4, 4) )
sns.regplot(x= "impact", y="originality", data = df, ax = axes[0,0] )
sns.regplot(x= "impact_KR", y="originality_KR", data = df, ax = axes[0,1] )
sns.regplot(x= "impact_MK", y="originality_MK", data = df, ax = axes[1,0] )
sns.regplot(x= "impact_PD", y="originality_PD", data = df, ax = axes[1,1] )
plt.tight_layout()
rho, p = ss.spearmanr(df['originality'], df['impact'])
axes[0,0].text( x = 20, y = 10, s = f"ρ = {rho:0.1f}")
axes[0,0].text( x = 20, y =  8, s = f"p = {p:0.3f}"  )
rho, p = ss.spearmanr(df['originality_KR'], df['impact_KR'])
axes[0,1].text( x =  7, y =  2, s = f"ρ = {rho:0.1f}" )
axes[0,1].text( x =  7, y =  1, s = f"p = {p:0.3f}"   )
rho, p = ss.spearmanr(df['originality_MK'], df['impact_MK'])
axes[1,0].text( x =  7, y =  3, s = f"ρ = {rho:0.1f}" )
axes[1,0].text( x =  7, y =  2, s = f"p = {p:0.3f}"   )
rho, p = ss.spearmanr(df['originality_PD'], df['impact_PD'])
axes[1,1].text( x =  7, y =  1, s = f"ρ = {rho:0.1f}" )
axes[1,1].text( x =  7, y =  0, s = f"p = {p:0.3f}"   )
plt.show()

fig, axes = plt.subplots( nrows = 3, ncols = 2, figsize = (4, 7) )
sns.regplot(x="originality_KR", y = "originality_MK", data = df, ax = axes[0,0] )
sns.regplot(x="originality_KR", y = "originality_PD", data = df, ax = axes[1,0] )
sns.regplot(x="originality_MK", y = "originality_PD", data = df, ax = axes[2,0] )
sns.regplot(x="impact_KR"     , y = "impact_MK"     , data = df, ax = axes[0,1] )
sns.regplot(x="impact_KR"     , y = "impact_PD"     , data = df, ax = axes[1,1] )
sns.regplot(x="impact_MK"     , y = "impact_PD"     , data = df, ax = axes[2,1] )
plt.tight_layout()
rho, p = ss.spearmanr(df['originality_KR'], df['originality_MK'])
axes[0, 0].text( x = 6, y = 2, s = f"ρ = {rho:0.3f}" )
rho, p = ss.spearmanr(df['originality_KR'], df['originality_PD'])
axes[1, 0].text( x = 6, y = 0, s = f"ρ = {rho:0.3f}" )
rho, p = ss.spearmanr(df['originality_MK'], df['originality_PD'])
axes[2, 0].text( x = 7, y = 0.5, s = f"ρ = {rho:0.3f}" )
rho, p = ss.spearmanr(df['impact_KR'], df['impact_MK'])
axes[0, 1].text( x = 7, y = 0, s = f"ρ = {rho:0.3f}" )
rho, p = ss.spearmanr(df['impact_KR'], df['impact_PD'])
axes[1, 1].text( x = 7, y = 0, s = f"ρ = {rho:0.3f}" )
rho, p = ss.spearmanr(df['impact_MK'], df['impact_PD'])
axes[2, 1].text( x = 6.5, y = 0.5, s = f"ρ = {rho:0.3f}" )
plt.show()
